USE EMPLOYEE;
SELECT *
FROM EMP;
SELECT Salary
FROM EMP;
SELECT DISTINCT COUNTY FROM EMP;
SELECT DISTINCT CITY,COUNTY FROM EMP;
SELECT * FROM EMP WHERE COUNTY = ('WALSH');
SELECT * FROM EMP WHERE COUNTY NOT IN ('POLK','STEFF');
SELECT * FROM EMP WHERE Year_of_Joining <= 2000;
SELECT AVG(SALARY) FROM EMP WHERE COUNTY = ('WALSH');
SELECT * FROM EMP WHERE First_Name = ('Domingo');
SELECT * FROM EMP WHERE SalarY > 50000;
SELECT LAST_NAME, GENDER, SALARY FROM EMP WHERE Date_of_Joining > ('01/01/2010');
SELECT LAST_NAME,Age_in_Yrs FROM EMP WHERE SALARY BETWEEN 10000 AND 60000;
